# Generated by Django 2.2.10 on 2021-09-26 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(default=' ', max_length=50)),
                ('card_status', models.CharField(choices=[('UNUSED', 'Unused'), ('IN_DECK', 'In Deck'), ('AVAILABLE_FOR_LOAN', 'Available for Loan'), ('LOANED_OUT', 'Loaned Out')], default='UNUSED', max_length=50)),
                ('card_rarity', models.CharField(default=' ', max_length=20)),
                ('card_set', models.CharField(default=' ', max_length=20)),
                ('card_cost', models.CharField(default=' ', max_length=20)),
                ('card_color', models.CharField(default=' ', max_length=20)),
                ('card_type', models.CharField(default=' ', max_length=50)),
                ('card_text', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_name', models.CharField(default=' ', max_length=50)),
                ('inventory_view_status', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=50)),
                ('inventory_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_request_status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='REQUESTED', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Loaner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loanee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loaned_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaned_inventory_name', models.CharField(default=' ', max_length=50)),
                ('loaned_inventory_view_status', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=50)),
                ('loaned_inventory_loanee_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Loanee')),
                ('loaned_inventory_loaner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Loaner')),
            ],
        ),
        migrations.CreateModel(
            name='Loaned_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_date', models.DateTimeField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Card')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Inventory')),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Loan_Request')),
                ('loaned_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Loaned_Inventory')),
            ],
        ),
        migrations.AddField(
            model_name='loan_request',
            name='loan_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Loaned_Inventory'),
        ),
        migrations.AddField(
            model_name='loan_request',
            name='loaner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Loaner'),
        ),
        migrations.AddField(
            model_name='loan_request',
            name='requestor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Loanee'),
        ),
        migrations.AddField(
            model_name='card',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Inventory'),
        ),
    ]
