# Generated by Django 3.2.8 on 2021-10-27 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaned_inventory',
            name='loaned_inventory_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.magic_user'),
        ),
        migrations.AddField(
            model_name='loaned_card',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.card'),
        ),
        migrations.AddField(
            model_name='loaned_card',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.inventory'),
        ),
        migrations.AddField(
            model_name='loaned_card',
            name='loan_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.loan_request'),
        ),
        migrations.AddField(
            model_name='loaned_card',
            name='loaned_inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.loaned_inventory'),
        ),
        migrations.AddField(
            model_name='loan_request',
            name='loanee_inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.loaned_inventory'),
        ),
        migrations.AddField(
            model_name='loan_request',
            name='loaner_inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.inventory'),
        ),
        migrations.AddField(
            model_name='loan_request',
            name='requestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.magic_user'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.magic_user'),
        ),
        migrations.AddField(
            model_name='card',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.inventory'),
        ),
    ]
