# Generated by Django 2.2.10 on 2021-09-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20210926_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_text',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
