# Generated by Django 3.2.9 on 2021-11-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='loan_request',
            options={'verbose_name_plural': 'Loan Requests'},
        ),
        migrations.AlterModelOptions(
            name='loaned_card',
            options={'verbose_name_plural': 'Loaned Cards'},
        ),
        migrations.AlterModelOptions(
            name='loaned_inventory',
            options={'verbose_name_plural': 'Loaned Inventories'},
        ),
        migrations.AddField(
            model_name='card',
            name='card_img_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
