# Generated by Django 3.2.9 on 2021-11-07 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20211106_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaned_card',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='loaned_card',
            name='loaned_inventory',
        ),
    ]
