# Generated by Django 3.2.8 on 2021-11-14 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('models', '0005_alter_card_card_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.magic_user'),
        ),
        migrations.AlterField(
            model_name='loaned_card',
            name='card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.card'),
        ),
        migrations.AlterField(
            model_name='loaned_inventory',
            name='loaned_inventory_owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.magic_user'),
        ),
    ]
