# Generated by Django 3.2.8 on 2021-11-14 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('models', '0006_auto_20211113_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='users.magic_user'),
        ),
        migrations.AlterField(
            model_name='loaned_inventory',
            name='loaned_inventory_owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loaned_inventory', to='users.magic_user'),
        ),
    ]
