# Generated by Django 3.2.8 on 2021-11-14 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0005_alter_card_card_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardWrapper',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.card')),
            ],
            bases=('models.card',),
        ),
        migrations.CreateModel(
            name='InventoryCountWrapper',
            fields=[
                ('inventory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.inventory')),
            ],
            bases=('models.inventory',),
        ),
        migrations.CreateModel(
            name='InventoryWrapper',
            fields=[
                ('inventory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.inventory')),
            ],
            bases=('models.inventory',),
        ),
    ]
