# Generated by Django 3.2.8 on 2021-11-15 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20211114_2006'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanedInventoryCountWrapper',
            fields=[
                ('loaned_inventory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.loaned_inventory')),
            ],
            bases=('models.loaned_inventory',),
        ),
    ]
