# Generated by Django 3.2.8 on 2021-11-14 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0005_alter_card_card_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Request_Wrapper',
            fields=[
                ('loan_request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.loan_request')),
            ],
            bases=('models.loan_request',),
        ),
    ]
